#!/bin/bash

rm *.pyc

rm *.csv

rm -rf ./notebooks/.ipynb_checkpoints/

cd ./docs/

if [ -d html ]; then

rm -rf ./ html

fi

cd ../tests/

rm *.pyc

cd ../game_graphs/

mv gradient1_003_thumb.png save

rm *.png 

mv save gradient1_003_thumb.png
